spring.application.name=football-quiz

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# TRACE
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.jdbc.datasource.init=DEBUG